theme: jekyll-theme-cayman
title: Thang Le
description: Who am I in this manipulated world? - A lost sheep seeking for piousness
url: https://azraelzhor.github.io
baseurl: ""
show_downloads: true

date_format: "%b %-d, %Y"


github:
  repository_url   : https://github.com/azraelzhor/azraelzhor.github.io

# Site Author
author:
  name             : "Thang Le"
  avatar           : "profile.png"
  bio              : "A lost sheep seeking for piousness"
  location         : "Vietnam"

  email            : "thanglecao0412@gmail.com"

  facebook         : "joocxi"
  github           : "azraelzhor"
  twitter          : "joocxi"
  cv_link          : https://drive.google.com/open?id=1HwlG0dtho6aN8zhkGk56OaC5N3gQpJd6
